services:
  web-server-portfolio:
    image: web-server-portfolio
    container_name: web-server-portfolio
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - docker/.docker.env
    volumes:
      - .:/var/www/html
    depends_on:
      - sql-server-portfolio
    ports:
      - "${APP_HOST_PORT}:80"
    links:
      - sql-server-portfolio
  sql-server-portfolio:
    image: postgres:latest
    container_name: sql-server-portfolio
    environment:
      # MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      # MYSQL_DATABASE: ${DB_DATABASE}
      # MYSQL_USER: ${DB_USERNAME}
      # MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./sql-data:/var/lib/postgresql/data
    ports:
      - "${DB_HOST_PORT}:5432"
